name: amazing_animated_widget
description: A Flutter package providing customizable animations for UI elements. It includes various animations such as circular, explosion, fade, flip, scale, and spiral.
homepage: https://github.com/OscarViana20/amazing_animated_widget
repository: https://github.com/OscarViana20/amazing_animated_widget

version: 0.0.2

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

topics:
  - ui
  - animation
  - animations

flutter:

  uses-material-design: true